version: '3.8'

services:
  app:
    build: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s
    command: node server.js
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nodedb
    networks:
      - app-network
    ports:
      - "3307:3306"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
