version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:      
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nodedb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
